dubbo:
  application:
    name: provider-ticket
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: com.weke.provider.service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weke?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb
mybatis:
  configuration:
    map-underscore-to-camel-case: true
