dubbo:
  application:
    name: provider-ticket
  registry:
    address: zookeeper://10.0.0.26:2181
  scan:
    base-packages: com.weke.provider.service
spring:
  datasource:
    url: jdbc:mysql://10.0.0.26:3306/weke?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
  http:
      multipart:
        max-file-size: 100Mb
        max-request-size: 1000Mb
  data:
    mongodb:
      uri: mongodb://10.0.0.26:12345/imooc
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      local: false
      repositories:
        enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true


weke.endpoint: oss-cn-beijing.aliyuncs.com
weke.keyId: LTAIXfxqPpwWg32d
weke.ketsecret: 5vWdV4dleGTHZU6H7c1wsXlYnAXqXV
weke.bucketname: weke-video
weke.filehost: video
